<?php

namespace Alba\Bundle\Repository;

/**
 * BreakfastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreakfastRepository extends \Doctrine\ORM\EntityRepository
{
}
