<?php

namespace Alba\Bundle\Repository;

/**
 * Order_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order_infoRepository extends \Doctrine\ORM\EntityRepository
{
}
